from typing import Annotated, Literal, Optional
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from IPython.display import display, Image
from dotenv import load_dotenv
from langchain.messages import SystemMessage
from langchain_openai import ChatOpenAI, data
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, StateGraph, add_messages
import sqlite3
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import AIMessage  , HumanMessage,trim_messages ,RemoveMessage
from langgraph.checkpoint.sqlite import SqliteSaver
import json
from pydantic import BaseModel, Field
import os
from utility.utility import savePNG, deleteGraphPNG


from prompts.prompts import (
    COMPANION_AGENT_PROMPT,
    GENERAL_AGENT_PROMPT,
    INTERVIEWER_AGENT_PROMPT,
    SUPERVISOR_PROMPT,
)



load_dotenv()
GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")

#Gloabal state / Notice board:  for all agents to access and update
class shared_state(BaseModel):
    is_locked: bool = False
    current_agent: str = "general_agent"
    next_agent: Optional[str] = None
    session_summary: str = ""
    general_session_summary: str = ""
    companion_session_summary: str = ""
    users_query: Optional[str] = None

    # Annotated fields already have a default of [] via add_messages
    general_memory: Annotated[list, add_messages] = []
    Companion_memory: Annotated[list, add_messages] = []
    


#supervisor should follow this respone model
class supervisor_response (BaseModel):
    next_agent : Literal["general_agent", "Interviewer_agent", "companion_agent", "Final_agent","trim_memory","long_memory_companion","long_memory_general"]=Field(
        description="The agent to route the query to next."
    )
    reasoning : str = Field(
        description="Reason for choosing the agent."
    )
    session_summary: str = Field(
        description="Summary of the conversation so far."
    )

global_fallback_model = ChatGoogleGenerativeAI(
    model="models/gemini-1.5-flash",
    google_api_key=GEMINI_API_KEY
)

# fallback model is openapi

supervisor_llm=ChatOpenAI (
    model= 'gpt-4o-mini',
    temperature=0.3
)

# DEFINING NODES
def supervisor(State: shared_state):
    # SUPERVISOR_PROMPT=ChatPromptTemplate.from_template(SUPERVISOR_PROMPT)

    if State.is_locked == True:
        next_agent = State.current_agent
        print("The state is locked. Routing to the current agent: ", next_agent)
        return {"next_agent":next_agent}

    if not State.general_memory:
        return {"next_agent":"general_agent"}
    
    latest_query= State.users_query

    llm_with_structured_output=supervisor_llm.with_structured_output(supervisor_response)
    SUPERVISOR_CHAIN=SUPERVISOR_PROMPT | llm_with_structured_output

    try:
        response=SUPERVISOR_CHAIN.invoke({
            "user_input" : latest_query,
            "is_locked": State.is_locked,
            "current_agent":State.current_agent
            # "session_summary": State.session_summary,
        })
        print("Supervisor's reasoning for choosing the next agent: ", response.reasoning)
        return {"next_agent":response.next_agent}
    except Exception as e:
        print("Error in supervisor chain , Rolling to General Agent: ", e)
        return {"next_agent":"general_agent"}  # default to general agent in case of error


# res=supervisor_llm.invoke("what are you doing?")
# print(res.content)


class worker_response(BaseModel):
    response_from_worker: str = Field(
        description="The response generated by the agent."
    )
    want_exit: Optional[bool] = Field(
        description="Flag indicating if the user wants to exit the companion mode."
    )

def trim_old_messages(State:shared_state, Agent_memory:str, Message_to_keep:int=6):
    '''Older messages will be trimmed and only the latest message will be send to the agent. 
    By this , we keep our sqlite memory small.
    '''

    actual_memory_list = getattr(State, Agent_memory, [])
    
    total_messages = len(actual_memory_list)

    if total_messages < Message_to_keep:
        return {}

    no_of_messages_tobe_trimmed=total_messages-Message_to_keep

    older_messages=actual_memory_list[:no_of_messages_tobe_trimmed]

    deletion_commands = [RemoveMessage(id=msg.id) for msg in older_messages]

    print("TRIMMED OLDER MESSAGE")
    return {f"{Agent_memory}": deletion_commands}

def trim_messages_general(State:shared_state):
    return trim_old_messages(State, "general_memory", 6)

def trim_messages_companion(State:shared_state):
    return trim_old_messages(State, "Companion_memory", 6)


def general_agent(State:shared_state):

    # Full context
    shared_context=State.general_session_summary

    #General Agent context + adding new user query to the context

    user_msg=HumanMessage(content=State.users_query)

    updated_memory=State.general_memory + [user_msg]
    
    # General Agent chat history
    recent_messages=updated_memory[-6:]  # last 6 messages

    llm_with_structured_output=supervisor_llm.with_structured_output(worker_response)

    GENERAL_CHAIN = GENERAL_AGENT_PROMPT | llm_with_structured_output
    try:
        response=GENERAL_CHAIN.invoke({
            "session_summary": shared_context,
            "recent_message": recent_messages
        })  # since we have not given it any fixed output schema, so it will be returning raw string. 

        return {"general_memory": [user_msg,AIMessage(response.response_from_worker)],
                "current_agent": "general_agent"}
    
    except Exception as e:
        print("Error in General Agent chain: ", e)
        return {"general_memory": [user_msg,AIMessage(content="Error in General Agent.")],
                "current_agent": "general_agent"}


# def final_agent(State:shared_state):

#     # Full context
#     shared_context=State.session_summary

#     # final Agent context
#     current_conversation=State.general_memory[-1].content

#     FINAL_AGENT_PROMPT=ChatPromptTemplate.from_template("""
#         You are the Final Agent. Your role is to summarize the entire conversation and provide a final response to the user.
#         """)
    

#     llm_with_structured_output=supervisor_llm.with_structured_output(worker_response)
#     FINAL_CHAIN = FINAL_AGENT_PROMPT | llm_with_structured_output
#     try:
#         response=FINAL_CHAIN.invoke({
#             "session_summary": shared_context,
#             "current_conversation": current_conversation,
#         })
#         final_response = response.response_from_worker
#         return {"final_memory": [AIMessage(final_response)],
#                 "current_agent": "final_agent"
#                 }
#     except Exception as e:
#         print("Error in Final Agent chain: ", e)
#         return {"final_memory": [AIMessage(content="Error in Final Agent.")],
#                 "current_agent": "final_agent"}

def companion_agent(State:shared_state):
    
    # Full context
    shared_context=State.companion_session_summary

    
    # Curret context

    user_msg=HumanMessage(content=State.users_query)

    updated_memory=State.Companion_memory + [user_msg]

    recent_messages=updated_memory[-6:]  # last 6 messages

    llm_with_structured_output=supervisor_llm.with_structured_output(worker_response)
    COMPANION_CHAIN = COMPANION_AGENT_PROMPT | llm_with_structured_output
    try:
        response=COMPANION_CHAIN.invoke({
            "session_summary": shared_context,
            "current_conversation": recent_messages,
        })
        companion_response = response.response_from_worker

        new_locked_status = True 
        new_agent = "companion_agent"
        
        if response.want_exit:
            print("Exiting companion mode...")
            new_locked_status = False
            new_agent = "general_agent"
            
        return {
            "Companion_memory": [user_msg,AIMessage(companion_response)],
            "current_agent": new_agent,
            "is_locked": new_locked_status
    }
    except Exception as e:
        print("Error in Companion Agent chain: ", e)
        return {"Companion_memory": [user_msg,AIMessage(content="Error in Companion Agent.")],
                "current_agent": new_agent,
                "is_locked": new_locked_status  # Locking the state even after error
                }


def long_memory_general(State:shared_state):
    memory_till_date=State.general_session_summary or "No Previous Summary"

    last_few_messages=State.general_memory[-6:]

    LONG_MEMORY_PROMPT=ChatPromptTemplate(
      [
          ("system", "You are a powerful content summarizer. Extract the important details from the content and make a powerful summary of the conversation"),
          ("human", "overall summary till date - {memory_till_date}"),
          ("human", "last few messages - {last_few_messages}")
      ]
    )

    chain= LONG_MEMORY_PROMPT | supervisor_llm
    res=chain.invoke({"memory_till_date":memory_till_date,"last_few_messages":last_few_messages})
    return {"general_session_summary":res.content}


def long_memory_companion(State: shared_state):
    # 1. Start with the existing summary
    old_summary = State.companion_session_summary or "No previous conversation."
    
    # 2. Get the new messages that haven't been summarized yet
    # (The last 6 messages)
    new_messages = State.Companion_memory[-6:]
    
    # 3. Create a PROPER recursive prompt
    summarize_prompt = ChatPromptTemplate.from_messages([
        ("system", "You are an expert summarizer. Update the existing summary of a conversation by incorporating new recent messages. Maintain all key facts, emotional states, and user details."),
        ("human", "Current Summary: {old_summary}"),
        ("human", "Recent conversation to add: {new_messages}"),
        ("human", "Provide the updated, comprehensive summary of the entire conversation so far.")
    ])

    # 4. Use the chain
    chain = summarize_prompt | supervisor_llm
    res = chain.invoke({
        "old_summary": old_summary, 
        "new_messages": new_messages
    })
    
    # 5. Return the full, updated summary
    return {"companion_session_summary": res.content}

def route_agent(State:shared_state):
    return State.next_agent

    
# def route
builder=StateGraph(shared_state)
builder.add_node("supervisor", supervisor)
builder.add_node("general_agent", general_agent)
builder.add_node("companion_agent", companion_agent)
builder.add_node("trim_messages_general", trim_messages_general) 
builder.add_node("trim_messages_companion", trim_messages_companion) 
builder.add_node("long_memory_general",long_memory_general)
builder.add_node("long_memory_companion",long_memory_companion)

builder.set_entry_point("supervisor")
builder.add_conditional_edges(
    "supervisor",
    route_agent,
    {
        "general_agent": "general_agent",
        "trim_messages_general": "trim_messages_general",
        "trim_messages_companion": "trim_messages_companion",
        
        "long_memory_general":"long_memory_general",
        "long_memory_companion":"long_memory_companion",


        # "Interviewer_agent": "interviewer_agent",
        "companion_agent": "companion_agent",
        # "Final_agent": "final_agent"
    }
)


builder.add_edge("general_agent", "trim_messages_general")
builder.add_edge("trim_messages_general", "long_memory_general")
builder.add_edge("long_memory_general",END)


builder.add_edge("companion_agent", "trim_messages_companion")
builder.add_edge("trim_messages_companion", "long_memory_companion")
builder.add_edge("long_memory_companion",END)
 


#compile
import time
current_time=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

#creating connection for sqllite saver
conn=sqlite3.connect(
    "agent_memory.db",
    check_same_thread=False
)

memory_checkpointer=SqliteSaver(conn=conn)
graph=builder.compile(checkpointer=memory_checkpointer)


config={
    "recursion_limit": 20,
    "configurable": {
        "thread_id": "session_001"
    }
}

# we are invoking these things only one time. 
# graph.invoke({
#     # "is_locked": False,
#     # "current_agent": "general_agent",
#     # "session_summary": "",
#     # "long_memory_general":"",
#     # "long_memory_companion":"",
#     # "general_memory": [],
#     # "Companion_memory": [],
#     "users_query": "" # Ensuring that the fresh conversation doesnt set none to users query, becase of which they may be problme in graph.
# }, config=config)

deleteGraphPNG(folder_path="/workspaces/LangGraph-practice/multiagent/SupervisorAgent/graph_PNG")
time.sleep(1)
savePNG(folderpath="/workspaces/LangGraph-practice/multiagent/SupervisorAgent/graph_PNG/",file_name=str(current_time),graph=graph)


while True: 
    user_input=input("User: ")

    if user_input.lower() in ["exit", "quit"]:
        print("Exiting the multi-agent system.")
        break
    if not user_input.strip():
        continue

    # THIS WAS CAUSE OF MEMORY LEAK. WE WILL EXTRACT THE USERS QUERY IN AGENT FUNTION ITSELF INSTEAD OF HERE.
    # new_input_payload = {
    #     "general_memory": [HumanMessage(content=user_input)],
    #     "Companion_memory": [HumanMessage(content=user_input)]
    # }


    updated_state = graph.invoke({
        "users_query": user_input,
    }, config=config)

    active_worker = updated_state.get("current_agent")
    
    if active_worker == "Companion_agent" or active_worker == "companion_agent":
        if updated_state.get("Companion_memory"):
            print("🤖 Companion Response: ", updated_state["Companion_memory"][-1].content)
    elif active_worker == "general_agent":
        if updated_state.get("general_memory"):
            print("🤖 General Response: ", updated_state["general_memory"][-1].content)
    else:
        print(f"🤖 [{active_worker}] Response: ", updated_state["general_memory"][-1].content)


    










    




